#!/bin/bash
set -euo pipefail

# ==============================================================================
# Run E2E Smoke Tests Locally (Both Modes)
# ==============================================================================
# This script runs smoke tests in both monolith and user-service modes,
# managing docker compose lifecycle automatically.
#
# Usage:
#   ./run-e2e-tests.sh                 # Run both modes
#   ./run-e2e-tests.sh --monolith      # Monolith only
#   ./run-e2e-tests.sh --user-service  # User-service only
# ==============================================================================

readonly GREEN='\033[0;32m'
readonly RED='\033[0;31m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly NC='\033[0m'

MODE="${1:-all}"

log_section() {
  echo ""
  echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
  echo -e "${BLUE}║${NC}  ${YELLOW}$1${NC}"
  printf "${BLUE}║${NC}  %-56s ${BLUE}║${NC}\n" " "
  echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
  echo ""
}

cleanup() {
  echo ""
  log_section "🧹 Cleaning up..."
  docker compose down -v 2>/dev/null || true
}

wait_for_health() {
  local url=$1
  local service_name=$2
  local max_wait=120

  echo -e "${BLUE}⏳${NC} Waiting for $service_name to be healthy (timeout: ${max_wait}s)..."

  local elapsed=0
  while [ $elapsed -lt $max_wait ]; do
    if curl -sf "$url" > /dev/null 2>&1; then
      echo -e "${GREEN}✓${NC} $service_name is ready!"
      return 0
    fi
    sleep 3
    elapsed=$((elapsed + 3))
    echo -n "."
  done

  echo ""
  echo -e "${RED}✗${NC} Timeout waiting for $service_name"
  return 1
}

run_monolith_mode() {
  log_section "🧪 Mode 1: Monolith (flag=false)"

  echo -e "${BLUE}→${NC} Building backend JAR..."
  cd backend
  ./mvnw clean package -DskipTests -q
  cd ..

  echo -e "${BLUE}→${NC} Starting services (postgres + redis + rabbitmq + backend)..."
  docker compose up -d postgres redis rabbitmq backend

  if ! wait_for_health "http://localhost:8080/actuator/health/readiness" "Backend"; then
    echo -e "${RED}ERROR: Backend failed to start${NC}"
    docker logs scopeflow-backend 2>&1 | tail -50
    return 1
  fi

  echo -e "${BLUE}→${NC} Running E2E tests..."
  export BASE_URL=http://localhost:8080
  export AUTH_SERVICE_EXTRACTED=false
  ./tests/e2e/auth-flow.test.sh

  local result=$?
  if [ $result -eq 0 ]; then
    echo -e "${GREEN}✓${NC} Monolith mode tests PASSED"
  else
    echo -e "${RED}✗${NC} Monolith mode tests FAILED"
  fi

  return $result
}

run_user_service_mode() {
  log_section "🧪 Mode 2: User Service (flag=true)"

  echo -e "${BLUE}→${NC} Building backend JAR..."
  cd backend
  ./mvnw clean package -DskipTests -q
  cd ..

  echo -e "${BLUE}→${NC} Building user-service JAR..."
  cd user-service
  ./mvnw clean package -DskipTests -q
  cd ..

  echo -e "${BLUE}→${NC} Creating .env with feature flag enabled..."
  cp .env.example .env
  echo "AUTH_SERVICE_EXTRACTED=true" >> .env
  echo "AUTH_SERVICE_URL=http://user-service:8081/api/v1" >> .env

  echo -e "${BLUE}→${NC} Starting services (all components + traefik)..."
  docker compose up -d

  if ! wait_for_health "http://localhost:8081/actuator/health/readiness" "User-service"; then
    echo -e "${RED}ERROR: User-service failed to start${NC}"
    docker logs scopeflow-user-service 2>&1 | tail -50
    return 1
  fi

  if ! wait_for_health "http://localhost:8080/actuator/health/readiness" "Backend"; then
    echo -e "${RED}ERROR: Backend failed to start${NC}"
    docker logs scopeflow-backend 2>&1 | tail -50
    return 1
  fi

  echo -e "${BLUE}→${NC} Verifying Traefik routing..."
  docker logs scopeflow-traefik 2>&1 | grep -E "(user-service|backend)" | tail -5 || true

  echo -e "${BLUE}→${NC} Running E2E tests..."
  export BASE_URL=http://localhost:8080
  export AUTH_SERVICE_EXTRACTED=true
  ./tests/e2e/auth-flow.test.sh

  local result=$?
  if [ $result -eq 0 ]; then
    echo -e "${GREEN}✓${NC} User-service mode tests PASSED"
    echo ""
    echo -e "${GREEN}🎉 JWT Compatibility Validated:${NC}"
    echo -e "   JWT generated by user-service was accepted by monolith"
    echo -e "   This confirms Strangler Fig migration is safe ✅"
  else
    echo -e "${RED}✗${NC} User-service mode tests FAILED"
  fi

  return $result
}

main() {
  trap cleanup EXIT

  log_section "🚀 E2E Smoke Tests - Local Runner"

  echo -e "${BLUE}Configuration:${NC}"
  echo -e "  Mode:          ${YELLOW}$MODE${NC}"
  echo -e "  Test script:   tests/e2e/auth-flow.test.sh"
  echo ""

  local monolith_result=0
  local user_service_result=0

  if [ "$MODE" = "all" ] || [ "$MODE" = "--monolith" ]; then
    run_monolith_mode || monolith_result=$?
    cleanup
  fi

  if [ "$MODE" = "all" ] || [ "$MODE" = "--user-service" ]; then
    run_user_service_mode || user_service_result=$?
    cleanup
  fi

  # Summary
  log_section "📊 Final Results"

  if [ "$MODE" = "all" ] || [ "$MODE" = "--monolith" ]; then
    if [ $monolith_result -eq 0 ]; then
      echo -e "${GREEN}✓${NC} Monolith mode:     PASSED"
    else
      echo -e "${RED}✗${NC} Monolith mode:     FAILED"
    fi
  fi

  if [ "$MODE" = "all" ] || [ "$MODE" = "--user-service" ]; then
    if [ $user_service_result -eq 0 ]; then
      echo -e "${GREEN}✓${NC} User-service mode: PASSED"
    else
      echo -e "${RED}✗${NC} User-service mode: FAILED"
    fi
  fi

  echo ""

  if [ $monolith_result -ne 0 ] || [ $user_service_result -ne 0 ]; then
    echo -e "${RED}⚠️  Some tests failed${NC}"
    exit 1
  else
    echo -e "${GREEN}🎉 All tests passed!${NC}"
    exit 0
  fi
}

main "$@"
